### ISSUE TITLE
Failing tests in 1.9.3

### ISSUE THREAD

**Issue by nomoon** [beverlycodes/orient_db_client#2]
I'm getting a lot of errors trying to run the test suites in 1.9.3. Not sure if it has to do with the gem versions you are running.

Unit test errors:

```
 1) Error:
test_updating_a_record(TestConnection):
NoMethodError: unmocked method :frozen?, expected one of []
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/object.rb:114:in `stubs'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:15:in `mock_connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/unit/connection_test.rb:8:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  2) Error:
test_opening_a_database(TestConnection):
NoMethodError: unmocked method :frozen?, expected one of []
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/object.rb:114:in `stubs'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:15:in `mock_connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/unit/connection_test.rb:8:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  3) Error:
test_creating_a_record(TestConnection):
NoMethodError: unmocked method :frozen?, expected one of []
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/object.rb:114:in `stubs'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:15:in `mock_connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/unit/connection_test.rb:8:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  4) Error:
test_opening_the_server(TestConnection):
NoMethodError: unmocked method :frozen?, expected one of []
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/object.rb:114:in `stubs'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:15:in `mock_connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/unit/connection_test.rb:8:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  5) Error:
test_creating_a_cluster(TestConnection):
NoMethodError: unmocked method :frozen?, expected one of []
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/object.rb:114:in `stubs'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:15:in `mock_connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/unit/connection_test.rb:8:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  6) Failure:
test_exception_on_unsupported_protocol(TestOrientDbClient) [C:/Users/Tim/Development/orient_db_client/test/unit/orient_db_client_test.rb:10]:
[OrientDbClient::UnsupportedProtocolError] exception expected, not
Class: <NoMethodError>
Message: <"unmocked method :frozen?, expected one of []">
```

Integration test errors:

```
1) Error:
test_establishing_a_connection(TestConnection):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/connection_test.rb:8:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  2) Error:
test_count(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  3) Error:
test_cluster_exists?(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  4) Error:
test_query(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  5) Error:
test_close(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  6) Error:
test_get_cluster_by_name(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  7) Error:
test_delete_cluster(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  8) Error:
test_reload(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

  9) Error:
test_create_cluster(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 10) Error:
test_load_record(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 11) Error:
test_get_cluster_datarange(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 12) Error:
test_get_cluster_by_id(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 13) Error:
test_create_and_delete_record(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 14) Error:
test_get_cluster_noexist(TestDatabaseSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/database_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 15) Error:
test_open_database(TestOpenDatabase):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/open_database_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 16) Error:
test_connect_command(TestOpenServer):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/open_server_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 17) Error:
test_create_and_delete_memory_database_commands(TestServerSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/server_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 18) Error:
test_create_and_delete_local_database_commands(TestServerSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/server_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

 19) Error:
test_database_exists_command(TestServerSession):
Errno::EINVAL: Invalid argument
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `pos'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:176:in `positioning_supported?'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/io.rb:44:in `initialize'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `new'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:159:in `read'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/bindata-1.4.3/lib/bindata/base.rb:50:in `read'
    C:/Users/Tim/Development/orient_db_client/lib/orient_db_client.rb:14:in `connect'
    C:/Users/Tim/Development/orient_db_client/test/support/connection_helper.rb:3:in `connect_to_orientdb'
    C:/Users/Tim/Development/orient_db_client/test/integration/server_session_test.rb:9:in `setup'
    C:/Dev/Ruby193/lib/ruby/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:26:in `run'

19 tests, 0 assertions, 0 failures, 19 errors, 0 skips
rake aborted!
Command failed with status (1): [C:/Dev/Ruby193/bin/ruby.exe -I"lib;lib" -I...]
```

**Comment by beverlycodes** [comment]
I'm unable to duplicate these errors using 1.9.3.  I'm noticing that while your path starts with Ruby193, your gems path lists 1.9.1.  Is it possible you've got some kind of mismatch between your Ruby version and your gem path?

If not, could you paste the output of `bundle` so that I can see which gem versions you're using?

**Comment by nomoon** [comment]
Here's the output of `bundle`:

```
Using rake (0.9.2.2)
Using bindata (1.4.3)
Using metaclass (0.0.1)
Using minitest (3.1.0)
Using mocha (0.11.4)
Using orient_db_client (0.0.4) from source at .
Using bundler (1.1.4)
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
```

The gems path listed there is the standard one generated by the installation. Even though it says "1.9.1" it only contains current gems, and shouldn't be the cause of any problems.

**Comment by beverlycodes** [comment]
I apologize for the long span with no updates.  I've fixed a bug that I found affecting the unit tests.  I've still not been able to duplicate the issue with the integration tests.

I did however add some more explicit versioning into the development dependencies to hopefully alleviate version mismatches between myself and other developers in the future.

If you're still watching this and still interested in this gem, please let me know if the 0.0.6 update resolves the testing problems on your end.  If I don't hear anything back in a week or so, I'll assume you've moved on to other solutions and will mark this closed.  If that happens, feel free to open the issue again if you return and find testing to still be broken.

**Comment by nomoon** [comment]
Ancient issue which I'm not sure matters anymore.
